name: Talentless
on:
  schedule:
  - cron: "*/10 2-3 * * *"
  - cron: "*/10 11-13 * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']
    steps:
    - uses: actions/checkout@v3

    - uses: browser-actions/setup-chrome@latest

    - name: Set up Ruby
      # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
      # change this to (see https://github.com/ruby/setup-ruby#versioning):
      # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        
    - name: Run script
      run: BROWSER_PATH=$(which chrome) bundle exec ruby talentless.rb
      env:
        TALENTLESS_EMAIL: ${{secrets.TALENTLESS_EMAIL}}
        TALENTLESS_PASSWORD: ${{secrets.TALENTLESS_PASSWORD}}
        TALENTLESS_LATITUDE: -7.811757317019967
        TALENTLESS_LONGITUDE: 112.01588003964854
        TALENTLESS_TIME_ZONE: +07:00
        TALENTLESS_HEADLESS: true
        TALENTLESS_SLACK_WEBHOOK: ${{secrets.TALENTLESS_SLACK_WEBHOOK}}
